---
# Created by @ZephrFish 
# https://zephrsec.com | https://blog.zsec.uk
galaxy_info:
  role_name: pivot_tools
  author: "@ZephrFish"
  description: Deploy pivot and tunneling tools (chisel, proxychains, SSH)
  version: "1.0.0"
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm

  galaxy_tags:
    - linux
    - security
    - pentest
    - pivoting
    - tunneling

dependencies: []
